const projects = [
  {
    id: 1,
    title: "Portafolio Personal",
    description: "Un sitio web responsive con Next.js y TailwindCSS.",
    image: "/images/proyectos/portafolio.png",
    tech: ["Next.js", "TailwindCSS", "Framer Motion"],
    github: "https://github.com/tuusuario/portafolio",
    demo: "https://tudominio.com",
  },
  {
    id: 2,
    title: "App de Notas",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/notas.png",
    tech: ["React", "CSS"],
    github: "https://github.com/tuusuario/app-notas",
    demo: "#",
  },
  {
    id: 3,
    title: "App de Notas",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/notas.png",
    tech: ["React", "CSS"],
    github: "https://github.com/tuusuario/app-notas",
    demo: "#",
  },
  {
    id: 4,
    title: "App de Notas",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/notas.png",
    tech: ["React", "CSS"],
    github: "https://github.com/tuusuario/app-notas",
    demo: "#",
  },
  {
    id: 5,
    title: "App de Notas",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/notas.png",
    tech: ["React", "CSS"],
    github: "https://github.com/tuusuario/app-notas",
    demo: "#",
  },
  {
    id: 6,
    title: "App de Notas",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/notas.png",
    tech: ["React", "CSS"],
    github: "https://github.com/tuusuario/app-notas",
    demo: "#",
  },
];

export default projects;
