const projects = [
  {
    id: 1,
    title: "Portafolio Personal",
    description: "Un sitio web responsive con Next.js y TailwindCSS.",
    image: "/images/proyectos/camdevportafolio.jpg",
    tech: ["TypeScript", "JavaScript", "CSS"],
    github: "https://github.com/tuusuario/portafolio",
    // demo: "#",
  },
  {
    id: 2,
    title: "Peluquería Admin",
    description: "Un sitio web responsive con Next.js y TailwindCSS.",
    image: "/images/proyectos/ ",
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/Cam-JR/peluqueria-admin",
    // demo: "#",
  },
  {
    id: 3,
    title: "Medical Center Web",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/medicalcenterweb.png",
    tech: ["HTML", "CSS", "PHP", "MySQL"],
    github: "https://github.com/Cam-JR/Medical-Center-Web",
    // demo: "#", 
  },
  {
    id: 4,
    title: "Music Fest EDM",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/musicfestedm.jpg",
    tech: ["SCSS", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/Cam-JR/Music-fest",
    demo: "https://musicfestedm.netlify.app/",
  }, 
  {
    id: 5,
    title: "Menú Estilo KFC",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/menuestilokfc.jpg",
    tech: ["HTML", "CSS"],
    github: "https://github.com/tuusuario/app-notas",
    demo: "https://menuestilokfc.netlify.app/#",
  },
  {
    id: 6,
    title: "Mexican Beer Bar",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/mexicanbeerbar.jpg",
    tech: ["HMLT", "CSS", "JavaScript"],
    github: "https://github.com/Cam-JR/Bar-Cervezas#",
    demo: "https://webarcerveza.netlify.app/#",
  },
  {
    id: 7,
    title: "Blog de Café",
    description: "Aplicación CRUD sencilla con React y LocalStorage.",
    image: "/images/proyectos/blogdecafe.jpg",
    tech: ["HTML", "CSS"],
    github: "https://github.com/Cam-JR/BlogCafe",
    demo: "https://webblogcafee.netlify.app/",
  },
];

export default projects;
