import { Type } from "lucide-react";

//projects.ts
const projects = [ 
  
  {
    id: 13,
    title: "Sistema MARCOBRE - Gestión Expediting & Correos",
    description:
      "Sistema diseñado para automatizar el seguimiento de expedientes y la gestión de correos, permitiendo consolidar información, actualizar reportes y optimizar los procesos operativos del área de Expediting.",
    image: "/images/projects/sistema-marcobre.jpg",
    tech: ["Python", "CustomTkinter", "Pandas", "OpenPyXL", "Excel"],
    // github: "https://github.com/Cam-JR/DentCare",
    // demo: "#",
    category: "Gestión",
  },
  {
    id: 12,
    title: "Sistema de Gestión de Proveedores",
    description:
      "Sistema que facilita la administración de proveedores mediante la búsqueda, filtrado y organización de registros, además de permitir la exportación de información para optimizar el control y seguimiento de datos.",
    image: "/images/projects/sistema-gestion-proveedores.jpeg",
    tech: ["Python", "CustomTkinter", "Pandas", "SQLite"],
    // github: "https://github.com/Cam-JR/DentCare",
    // demo: "#",
    category: "Gestión",
  },
  {
    id: 11,
    title: "DentCare",
    description:"Sistema que gestiona pacientes y automatiza procesos odontológicos.",
    image: "/images/projects/dentcare.png ",
    tech: ["HTML", "CSS", "JavaScript", "MySQL", "React", "UX/UI"],  
    github: "https://github.com/Cam-JR/DentCare",
    // demo: "#",
    category: "Website",
  },
  {
    id: 10,
    title: "App de Presupuesto",
    description: "Aplicación para gestionar ingresos y gastos, permitiendo calcular el balance total. Ofrece una interfaz que facilita el control financiero.",
    image: "/images/projects/calculadora-presupuesto.png ",
    tech: ["HTML", "CSS", "JavaScript"],  
    github: "https://github.com/Cam-JR/MINI-PROJECTS/tree/master?tab=readme-ov-file",
    demo: "https://appresupuestos.netlify.app/",
    category: "Personal",
  },
  {
    id: 9,
    title: "Calculadora BMI",
    description: "Aplicación web que calcula el Índice de Masa Corporal y muestra la categoría correspondiente. Incluye cálculo del peso ideal.",
    image: "/images/projects/calculadora-bmi.png ",
    tech: ["HTML", "CSS", "JavaScript", "UX"],
    github: "https://github.com/Cam-JR/MINI-PROJECTS/tree/master?tab=readme-ov-file",
    demo: "https://calculadoradebmi.netlify.app/",
    category: "Personal",
  },
  {
    id: 8,
    title: "Generador de CSS",
    description: "Herramienta visual que permite modificar propiedades CSS en tiempo real. También permite subir imágenes.",
    image: "/images/projects/css-generador.jpg ",
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/Cam-JR/MINI-PROJECTS/tree/master?tab=readme-ov-file",
    demo: "https://css-generador.netlify.app/",
    category: "Personal",
  },
  {
    id: 7,
    title: "ToDo List",
    description: "Aplicación para gestionar tareas: add, edit, delete mediante drag & drop. Incluye filtros, búsqueda, notificaciones.",
    image: "/images/projects/todo-list.png ",
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/Cam-JR/MINI-PROJECTS/tree/master?tab=readme-ov-file",
    demo: "https://todolistcam.netlify.app/",
    category: "Personal",
  },
  {
    id: 6,
    title: "Stop Watch",
    description: "Cronómetro web con funciones de Start, Stop y Reset, además de modo oscuro.",
    image: "/images/projects/stop-watch.jpg",
    tech: ["HTML", "CSS"],
    github: "https://github.com/Cam-JR/MINI-PROJECTS/tree/master?tab=readme-ov-file",
    demo: "https://stoppwatchhh.netlify.app/",
    category: "Personal",
  },
  {
    id: 5,
    title: "Organizador de Archivos",
    description: "Aplicación de escritorio que permite organizar tus archivos. Ideal para mantener carpetas ordenadas fácilmente con una interfaz visual.",
    image: "/images/projects/organizador-archivos.png",
    tech: ["Python", "JavaScript", "CSS", "HTML"],
    github: "https://github.com/Cam-JR/Organizador-de-archivos",
    // demo: "#",
    category: "Personal",
  },
  {
    id: 4,
    title: "Portafolio Personal",
    description: "Un sitio web responsive sobre mí y mis proyectos.",
    image: "/images/projects/camdev-portafolio.jpg",
    tech: ["TypeScript", "JavaScript", "CSS", "React"],
    github: "https://github.com/Cam-JR/Cam-Portafolio",
    demo: "https://cam-portafolio.vercel.app/",
    category: "Website",
  },
  {
    id: 3,
    title: "Peluquería Admin",
    description: "Panel administrativo pensado para la gestión de citas y servicios de peluquería.",
    image: "/images/projects/peluqueri-admin.jpg",
    tech: ["HTML", "CSS", "JavaScript", "TypeScript"], 
    github: "https://github.com/Cam-JR/peluqueria-admin",
    // demo: "#",
    category: "Website",
  },
  {
    id: 2,
    title: "Medical Center Web",
    description: "Página institucional orientada a un centro médico con apartados de servicios y contacto.",
    image: "/images/projects/medical-center-web.png",
    tech: ["HTML", "CSS", "PHP", "MySQL"],
    github: "https://github.com/Cam-JR/Medical-Center-Web",
    // demo: "#", 
    category: "Website",
  },
  {
    id: 1,
    title: "Mexican Beer Bar",
    description: "Landing page que presenta la oferta de un bar con secciones de productos y servicios.",
    image: "/images/projects/mexican-beerbar.jpg",
    tech: ["HMLT", "CSS", "JavaScript"],
    github: "https://github.com/Cam-JR/Bar-Cervezas#",
    demo: "https://webarcerveza.netlify.app/#",
    category: "Website",
  },
  {
    id: 0,
    title: "Blog de Café",
    description: "Blog diseñado con un estilo moderno y enfocado en artículos relacionados al café.",
    image: "/images/projects/blog-cafe.jpg",
    tech: ["HTML", "CSS"],
    github: "https://github.com/Cam-JR/BlogCafe",
    demo: "https://webblogcafee.netlify.app/",
    category: "Blog",
  },
];

export default projects;
